apiVersion: v1
kind: Service
metadata:
  name: gameserver
spec:
  type: NodePort
  selector:
    app: gameserver
  ports:
  - port: 30000
    nodePort: 30000
---
apiVersion: v1
kind: Service
metadata:
  name: commonwealth-game-server
spec:
  selector:
    app: gameserver
  ports:
    - port: 30042