apiVersion: apps/v1
kind: Deployment
metadata:
  name: globalserver
  labels:
    app: globalserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: globalserver
  template:
    metadata:
      labels:
        app: globalserver
    spec:
      containers:
        - name: globalserver
          image: sebitommy123/global_server:latest
          ports:
            - containerPort: 30002
              name: globalserver
          env:
            - name: MY_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: globalserver
                  key: endpoint
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: globalserver
                  key: port
            - name: CLIENTORIGIN
              valueFrom:
                configMapKeyRef:
                  name: general
                  key: client_url_origin
            - name: REGIONS
              valueFrom:
                configMapKeyRef:
                  name: globalserver
                  key: regions
          volumeMounts:
            - mountPath: /etc/letsencrypt/live/commonwealth.zubatomic.com
              name: ssl
              readOnly: true
      volumes:
        - name: ssl
          secret:
            secretName: ssl
            optional: true
