apiVersion: apps/v1
kind: Deployment
metadata:
  name: mainserver
  labels:
    app: mainserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mainserver
  template:
    metadata:
      labels:
        app: mainserver
    spec:
      containers:
        - name: mainserver
          image: sebitommy123/main_server:latest
          ports:
            - containerPort: 30010
              name: mainserver
            - containerPort: 30011
              name: mainserver-int
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: mainserver
                  key: port
            - name: INTERNAL_PORT
              valueFrom:
                configMapKeyRef:
                  name: mainserver
                  key: internal_port
            - name: CLIENTORIGIN
              valueFrom:
                configMapKeyRef:
                  name: general
                  key: client_url_origin
            - name: MY_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: mainserver
                  key: endpoint
            - name: REGION
              valueFrom:
                configMapKeyRef:
                  name: mainserver
                  key: region
            - name: AWS_REGION
              valueFrom:
                secretKeyRef:
                  name: aws
                  key: region
            - name: DDB_TABLE_NAME
              valueFrom:
                secretKeyRef:
                  name: aws
                  key: ddb_table_name
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws
                  key: access_key_id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws
                  key: secret_access_key
          volumeMounts:
            - mountPath: /etc/letsencrypt/live/commonwealth.zubatomic.com
              name: ssl
              readOnly: true
      volumes:
        - name: ssl
          secret:
            secretName: ssl
            optional: true